version: '3.8'

services:
  # Database MySQL cho Laravel
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Container cho Laravel
  app:
    build:
      context: ./backend_laravel
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./backend_laravel:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8000:80"
    depends_on:
      - db

  # Container cho Vue
  frontend:
    build:
      context: ./frontend_vuejs
      dockerfile: Dockerfile
    image: vue_app
    container_name: vue_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./frontend_vuejs:/app
    command: npm run dev

  # Container cho phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini

volumes:
  db_data:
