<?php

namespace Tests\Feature;

use App\Enums\Status;
use App\Http\Middleware\JwtMiddleware;
use App\Models\Category;
use App\Models\Country;
use App\Models\Genre;
use App\Models\Movie;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Str;
use Tests\TestCase;

class MovieTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware(JwtMiddleware::class);
    }

    public function test_movie_list(): void
    {
        $response = $this->getJson('api/movie');
        $response->assertStatus(200);
        $response->assertJsonStructure([
            'success',
            'data' => [
                'data',
                'links',
                'meta'
            ]
        ]);
    }

    public function test_movie_search_by_keyword(): void
    {
        $keyword = 'test';
        $response = $this->getJson('api/movie?keyword=' . $keyword);
        $response->assertStatus(200);
        $response->assertJsonStructure([
            'success',
            'data' => [
                'data',
                'links',
                'meta'
            ]
        ]);
    }

    public function test_movie_store_success(): void
    {
        $genre1 = Genre::factory()->create();
        $genre2 = Genre::factory()->create();
        $country = Country::factory()->create();
        $category = Category::factory()->create();

        $response = $this->postJson('api/movie', [
            'name' => 'test name',
            'slug' => 'test-slug',
            'origin_name' => 'test origin name',
            'content' => 'test content',
            'type' => 1,
            'status' => 1,
            'poster_url' => 'https://example.com/poster.jpg',
            'thumb_url' => 'https://example.com/thumb.jpg',
            'is_copyright' => true,
            'sub_docquyen' => true,
            'chieurap' => true,
            'trailer_url' => 'https://example.com/trailer.mp4',
            'time' => '120 min',
            'episode_current' => '1',
            'episode_total' => 10,
            'quality' => 1,
            'lang' => 'English',
            'notify' => 'Notify message',
            'showtimes' => '20:00',
            'year' => 2021,
            'actor' => ['Actor 1', 'Actor 2'],
            'director' => ['Director 1'],
            'genre_ids' => [$genre1->id, $genre2->id],
            'country_id' => $country->id,
            'category_id' => $category->id,
        ]);

        $response->assertStatus(201);
        $response->assertJsonStructure([
            'success',
            'data'
        ]);
    }

    /**
     * @dataProvider movieDataProvider
     */
    public function test_movie_store_failed($name = null, $slug = null, $origin_name = null, $content = null, $type = null, $status = null, $poster_url = null, $thumb_url = null, $is_copyright = null, $sub_docquyen = null, $chieurap = null, $trailer_url = null, $time = null, $episode_current = null, $episode_total = null, $quality = null, $lang = null, $notify = null, $showtimes = null, $year = null, $actor = null, $director = null, $genre_ids = null, $country_id = null, $category_id = null): void
    {
        $genre1 = Genre::factory()->create();
        $genre2 = Genre::factory()->create();
        $country = Country::factory()->create();
        $category = Category::factory()->create();

        $testGenre = $genre_ids ?? [$genre1->id, $genre2->id];
        $testCountry = $country_id ?? $country->id;
        $testCategory = $category_id ?? $category->id;

        $response = $this->postJson('api/movie', [
            'name' => $name,
            'slug' => $slug,
            'origin_name' => $origin_name,
            'content' => $content,
            'type' => $type,
            'status' => $status,
            'poster_url' => $poster_url,
            'thumb_url' => $thumb_url,
            'is_copyright' => $is_copyright,
            'sub_docquyen' => $sub_docquyen,
            'chieurap' => $chieurap,
            'trailer_url' => $trailer_url,
            'time' => $time,
            'episode_current' => $episode_current,
            'episode_total' => $episode_total,
            'quality' => $quality,
            'lang' => $lang,
            'notify' => $notify,
            'showtimes' => $showtimes,
            'year' => $year,
            'actor' => $actor,
            'director' => $director,
            'genre_ids' => $testGenre,
            'country_id' => $testCountry,
            'category_id' => $testCategory,
        ]);

        $response->assertStatus(422);
        $response->assertJsonStructure([
            'message',
            'errors',
        ]);
    }

    public function test_movie_show_success(): void
    {
        $movie = Movie::factory()->create();
        $response = $this->getJson('api/movie/' . $movie->slug);
        $response->assertStatus(200);
        $response->assertJsonStructure([
            'success',
            'data'
        ]);
    }

    public function test_movie_show_failed(): void
    {
        $response = $this->getJson('api/movie/1');
        $response->assertStatus(404);
    }

    public function test_movie_update_success(): void
    {
        $genre1 = Genre::factory()->create();
        $genre2 = Genre::factory()->create();
        $country = Country::factory()->create();
        $category = Category::factory()->create();

        $movie = Movie::factory()->create();
        $response = $this->putJson("api/movie/{$movie->slug}", [
            'name' => 'test name',
            'slug' => 'test-slug',
            'origin_name' => 'test origin name',
            'content' => 'test content',
            'type' => 1,
            'status' => 1,
            'poster_url' => 'https://example.com/poster.jpg',
            'thumb_url' => 'https://example.com/thumb.jpg',
            'is_copyright' => true,
            'sub_docquyen' => true,
            'chieurap' => true,
            'trailer_url' => 'https://example.com/trailer.mp4',
            'time' => '120 min',
            'episode_current' => '1',
            'episode_total' => 10,
            'quality' => 1,
            'lang' => 'English',
            'notify' => 'Notify message',
            'showtimes' => '20:00',
            'year' => 2021,
            'actor' => ['Actor 1', 'Actor 2'],
            'director' => ['Director 1'],
            'genre_ids' => [$genre1->id, $genre2->id],
            'country_id' => $country->id,
            'category_id' => $category->id,
        ]);
        $response->assertStatus(200);
        $response->assertJsonStructure([
            'success',
            'data'
        ]);
    }

    /**
     * @dataProvider movieDataProvider
     */
    public function test_movie_update_failed($name = null, $slug = null, $origin_name = null, $content = null, $type = null, $status = null, $poster_url = null, $thumb_url = null, $is_copyright = null, $sub_docquyen = null, $chieurap = null, $trailer_url = null, $time = null, $episode_current = null, $episode_total = null, $quality = null, $lang = null, $notify = null, $showtimes = null, $year = null, $actor = null, $director = null, $genre_ids = null, $country_id = null, $category_id = null): void
    {
        $genre1 = Genre::factory()->create();
        $genre2 = Genre::factory()->create();
        $country = Country::factory()->create();
        $category = Category::factory()->create();

        $testGenre = $genre_ids ?? [$genre1->id, $genre2->id];
        $testCountry = $country_id ?? $country->id;
        $testCategory = $category_id ?? $category->id;
        $movie = Movie::factory()->create();

        $response = $this->putJson("api/movie/{$movie->slug}", [
            'name' => $name,
            'slug' => $slug,
            'origin_name' => $origin_name,
            'content' => $content,
            'type' => $type,
            'status' => $status,
            'poster_url' => $poster_url,
            'thumb_url' => $thumb_url,
            'is_copyright' => $is_copyright,
            'sub_docquyen' => $sub_docquyen,
            'chieurap' => $chieurap,
            'trailer_url' => $trailer_url,
            'time' => $time,
            'episode_current' => $episode_current,
            'episode_total' => $episode_total,
            'quality' => $quality,
            'lang' => $lang,
            'notify' => $notify,
            'showtimes' => $showtimes,
            'year' => $year,
            'actor' => $actor,
            'director' => $director,
            'genre_ids' => $testGenre,
            'country_id' => $testCountry,
            'category_id' => $testCategory,
        ]);

        $response->assertStatus(422);
        $response->assertJsonStructure([
            'message',
            'errors',
        ]);
    }

    public function test_movie_delete_success(): void
    {
        $movie = Movie::factory()->create();

        $response = $this->deleteJson("api/movie/{$movie->slug}");

        $response->assertStatus(200);
        $response->assertJsonStructure([
            'success',
            'data'
        ]);

        $this->assertDatabaseMissing('movies', [
            'id' => $movie->id,
        ]);
    }

    public function test_movie_delete_failed(): void
    {
        $nonExistentMovieSlug = 'non-existent-movie-slug';

        $response = $this->deleteJson("api/movie/{$nonExistentMovieSlug}");

        $response->assertStatus(404);
    }

    public function test_movie_store_unique_slug_failed(): void
    {
        $genre1 = Genre::factory()->create();
        $genre2 = Genre::factory()->create();
        $country = Country::factory()->create();
        $category = Category::factory()->create();
        $movie = Movie::factory()->create(['slug' => 'test-slug']);

        $response = $this->postJson('api/movie', [
            'name' => 'another test name',
            'slug' => 'test-slug',
            'origin_name' => 'another test origin name',
            'content' => 'another test content',
            'type' => 1,
            'status' => 1,
            'poster_url' => 'https://example.com/poster.jpg',
            'thumb_url' => 'https://example.com/thumb.jpg',
            'is_copyright' => true,
            'sub_docquyen' => true,
            'chieurap' => true,
            'trailer_url' => 'https://example.com/trailer.mp4',
            'time' => '120 min',
            'episode_current' => '1',
            'episode_total' => 10,
            'quality' => 1,
            'lang' => 'English',
            'notify' => 'Notify message',
            'showtimes' => '20:00',
            'year' => 2021,
            'actor' => ['Actor 1', 'Actor 2'],
            'director' => ['Director 1'],
            'genre_ids' => [$genre1->id, $genre2->id],
            'country_id' => $country->id,
            'category_id' => $category->id,
        ]);

        $response->assertStatus(422);
        $response->assertJsonStructure([
            'errors',
        ]);
    }

    public function test_movie_update_unique_slug_failed(): void
    {
        $genre1 = Genre::factory()->create();
        $genre2 = Genre::factory()->create();
        $country = Country::factory()->create();
        $category = Category::factory()->create();
        $movie1 = Movie::factory()->create(['slug' => 'test-slug-1']);
        $movie2 = Movie::factory()->create(['slug' => 'test-slug-2']);

        $response = $this->putJson("api/movie/{$movie2->slug}", [
            'name' => 'updated test name',
            'slug' => 'test-slug-1',
            'origin_name' => 'updated test origin name',
            'content' => 'updated test content',
            'type' => 1,
            'status' => 1,
            'poster_url' => 'https://example.com/poster.jpg',
            'thumb_url' => 'https://example.com/thumb.jpg',
            'is_copyright' => true,
            'sub_docquyen' => true,
            'chieurap' => true,
            'trailer_url' => 'https://example.com/trailer.mp4',
            'time' => '120 min',
            'episode_current' => '1',
            'episode_total' => 10,
            'quality' => 1,
            'lang' => 'English',
            'notify' => 'Notify message',
            'showtimes' => '20:00',
            'year' => 2021,
            'actor' => ['Actor 1', 'Actor 2'],
            'director' => ['Director 1'],
            'genre_ids' => [$genre1->id, $genre2->id],
            'country_id' => $country->id,
            'category_id' => $category->id,
        ]);

        $response->assertStatus(422);
        $response->assertJsonStructure([
            'errors',
        ]);
    }

    public static function movieDataProvider(): array
    {

        return [
            // Name
            'Without name' => [
                'name' => null,
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Name too long' => [
                'name' => Str::random(256),
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Slug
            'Without slug' => [
                'name' => 'test name',
                'slug' => null,
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Slug too long' => [
                'name' => 'test-name',
                'slug' => Str::random(256),
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Origin name
            'Without origin_name' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => null,
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Origin Name too long' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => Str::random(256),
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Content
            'Without content' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => null,
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Type
            'Without type' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => null,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Type too large' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => PHP_INT_MAX,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid type (not an int)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 'string',
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid type (not in list)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 4,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Status
            'Without status' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => null,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Status too large' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => PHP_INT_MAX,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid status (not an int)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 'string',
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid status (not in list)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 3,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Poster url
            'Without poster_url' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => null,
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Poster_url too long' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => Str::random(256),
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Thumb url
            'Without thumb_url' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => null,
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Thumb_url too long' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => Str::random(256),
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // is_copyright
            'Without is_copyright' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => null,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid is_copyright (not a boolean)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => 'string',
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // sub_docquyen
            'Without sub_docquyen' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => null,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid sub_docquyen (not a boolean)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => 'string',
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // chieurap
            'Without chieurap' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => null,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid chieurap (not a boolean)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => 'string',
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // trailer_url
            'trailer_url too long' => [
                'name' => 'test-name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => Str::random(256),
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // time
            'time too long' => [
                'name' => 'test-name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => Str::random(256),
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // episode_current
            'episode_current too long' => [
                'name' => 'test-name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => Str::random(256),
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // episode_total
            'episode_total too large' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => PHP_INT_MAX,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid episode_total (not an int)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 'string',
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Quality
            'Invalid quality (not an int)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 'string',
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid quality (not in list)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 4,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Lang
            'lang too long' => [
                'name' => 'test-name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => Str::random(256),
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // notify
            'notify too long' => [
                'name' => 'test-name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'VN',
                'notify' => Str::random(256),
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // showtimes
            'showtimes too long' => [
                'name' => 'test-name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'vn',
                'notify' => 'Notify message',
                'showtimes' => Str::random(256),
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Year
            'Without year' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => null,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid year (not an int)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid year (too low)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 1899,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid year (too hight)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => date('Y') + 1,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Actor
            'Without actor' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => null,
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid actor (not an array)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => 'Actor',
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid actor element (not an string)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => ['Actor 1', 'Actor 2', ['Actor 3']],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid actor element (too long)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => ['Actor 1', 'Actor 2', Str::random(256)],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Director
            'Without director' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => null,
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid director (not an array)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => 'Director 1',
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid director element (not an string)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1', 'Director 2', ['Director 3']],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid director element (too long)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1', 'Director 2', Str::random(256)],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => null,
            ],
            // Genre
            'Invalid genre_ids (not an array)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => ['Actor'],
                'director' => ['Director 1'],
                'genre_ids' => 'string',
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid genre_ids element (not an int)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 1,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 'string',
                'actor' => ['Actor'],
                'director' => ['Director 1'],
                'genre_ids' => ['string'],
                'country_id' => null,
                'category_id' => null,
            ],
            'Invalid genre_ids element (not exists)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [999],
                'country_id' => null,
                'category_id' => null,
            ],
            // Country
            'Invalid country_id (not exists)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => 999,
                'category_id' => null,
            ],
            // Category
            'Invalid category_id (not exists)' => [
                'name' => 'test name',
                'slug' => 'test-slug',
                'origin_name' => 'test origin name',
                'content' => 'test content',
                'type' => 1,
                'status' => 1,
                'poster_url' => 'https://example.com/poster.jpg',
                'thumb_url' => 'https://example.com/thumb.jpg',
                'is_copyright' => true,
                'sub_docquyen' => true,
                'chieurap' => true,
                'trailer_url' => 'https://example.com/trailer.mp4',
                'time' => '120 min',
                'episode_current' => '1',
                'episode_total' => 10,
                'quality' => 1,
                'lang' => 'English',
                'notify' => 'Notify message',
                'showtimes' => '20:00',
                'year' => 2021,
                'actor' => ['Actor 1', 'Actor 2'],
                'director' => ['Director 1'],
                'genre_ids' => [],
                'country_id' => null,
                'category_id' => 999,
            ],
        ];
    }
}
